language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "fBISI40WKTrtHMTbuRV6rYYGkJGAbFYfjIxB7WQMCeuBVHsf7xPqjRRP2mqQOxlm+XfT2ClVslmnlCPMON61VxKWiwFERNObC4STO6j4N79wA2+I0wGTUY47tY9i0ngS9Dhe7BtCBPpIYvY68VV1SvLI+6tNN0MT1PBq3ZKDEuU="
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm config set loglevel error"
  - "npm i -g npm@\"^2.0.0\""
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash && cd ./node_modules/lodash && npm i && cd ../../"
  - "npm i -g coveralls@\"^2.0.0\" istanbul@\"0.3.2\""
script:
  - "istanbul instrument --output ./modern-coverage ./modern"
  - "phantomjs --disk-cache=true ./node_modules/lodash/test/test.js \"node_modules/lodash/test/index.html?build=../../../modern-coverage/main.js&loader=requirejs&noglobals=true\""
  - "istanbul report lcovonly"
  - "[ $TRAVIS_SECURE_ENV_VARS == true ] && cat ./coverage/lcov.info | coveralls || true"
