language: node_js
sudo: false
node_js:
  - "0.12"
env:
  global:
    - PATTERN="s|\s*else\s*\{\s*iteratee\(index\);\s*\}||"
    - secure: "fBISI40WKTrtHMTbuRV6rYYGkJGAbFYfjIxB7WQMCeuBVHsf7xPqjRRP2mqQOxlm+XfT2ClVslmnlCPMON61VxKWiwFERNObC4STO6j4N79wA2+I0wGTUY47tY9i0ngS9Dhe7BtCBPpIYvY68VV1SvLI+6tNN0MT1PBq3ZKDEuU="
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm config set loglevel error"
  - "npm i -g npm@\"^2.0.0\""
  - "npm i -g coveralls@\"^2.0.0\" istanbul@\"0.3.17\""
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash ./node_modules/lodash && cd $_ && perl -pi -e 's|\"lodash\"|\"lodash-compat\"|' ./package.json && npm i && cd ../../"
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli ./node_modules/lodash-cli && mkdir $_/node_modules && cd $_ && ln -s ../../lodash/ ./lodash-compat && cd ../ && npm i && cd ../../"
  - "node ./node_modules/lodash-cli/bin/lodash modularize modern exports=amd -o ./modern"
  - "perl -0pi -e \"$PATTERN\" ./modern/utility/times.js"
script:
  - "istanbul instrument --output ./modern-coverage ./modern"
  - "phantomjs --disk-cache=true ./node_modules/lodash/test/test.js \"node_modules/lodash/test/index.html?build=../../../modern-coverage/main.js&loader=requirejs&noglobals=true\""
  - "istanbul report lcovonly"
  - "[ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/lcov.info | coveralls) || true"
